#version: '3.9'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: sqs,s3
      #DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"
    volumes:
      - localstack:/var/lib/localstack
      - ./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      #- /var/run/docker.sock:/var/run/docker.sock

  backend:
    build:
      context: ../app/backend
    depends_on:
      - postgres
      - localstack
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: myapp
      DB_PASSWORD: password
      DB_NAME: myapp_db
      AWS_REGION: us-east-1
      SQS_QUEUE_URL: http://localstack:4566/000000000000/my-queue

  frontend:
    build:
      context: ../app/frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: http://backend:3000
    depends_on:
    - backend
    ports:
    - "80:80"

  lambda-mock:
    build:
      context: ./lambda-mock
    depends_on:
      - s3-init
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      AWS_ENDPOINT: http://localstack:4566
      SQS_QUEUE_URL: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/my-queue
      S3_BUCKET_NAME: myapp-bucket

  s3-init:
    image: amazon/aws-cli
    container_name: s3-init
    depends_on:
      - localstack
    entrypoint: >
      /bin/sh -c "
        aws --endpoint-url=http://localstack:4566 --region us-east-1 s3 mb s3://myapp-bucket || true
      "
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test

volumes:
  pgdata:
  localstack: