#!/bin/bash

# Load the base .env file
set -a
source ./env.base.generate/.env.base
set +a

envsubst < ./skaffold/templates/skaffold-frontend.yaml.template > ./skaffold/skaffold-frontend.yaml
  envsubst < ./skaffold/templates/skaffold-backend.yaml.template > ./skaffold/skaffold-backend.yaml

