apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frontend-app-secrets
  namespace: frontend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: frontend-app-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: project-5-frontend-envs
