apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-app-secrets
  namespace: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: backend-app-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: project-5-backend-envs
