{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include (printf "%s.fullname" .Chart.Name) . }}
  labels:
    {{ include (printf "%s.labels" .Chart.Name) . }}
  annotations:
    {{ required "ingress.annotations.rewriteTarget is required" .Values.ingress.annotations.rewriteTarget }}: "{{ required "ingress.annotations.rewriteValue is required" .Values.ingress.annotations.rewriteValue }}"
spec:
  rules:
    - host: {{ required "ingress.host is required" .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include (printf "%s.fullname" .Chart.Name) . }}
                port:
                  name: http
{{- end }}