apiVersion: v1
kind: Secret
metadata:
  name: {{ include (printf "%s.fullname" .Chart.Name) . }}-env
  labels:
    {{ include (printf "%s.labels" .Chart.Name) . }}
type: Opaque
stringData:
{{- range $key, $value := .Values.envSecrets }}
  {{ $key }}: {{ required (printf "Missing value for envSecrets.%s" $key) $value | quote }}
{{- end }}