apiVersion: v1
kind: Service
metadata:
  name: {{ include (printf "%s.fullname" .Chart.Name) . }}
  labels:
    {{ include (printf "%s.labels" .Chart.Name) . }}
spec:
  type: {{ required "service.type is required" .Values.service.type }}
  selector:
    app: {{ include (printf "%s.fullname" .Chart.Name) . }}
  ports:
    - name: http
      port: {{ required "service.port is required" .Values.service.port }}
      targetPort: {{ required "containerPort is required" .Values.containerPort }}