name: Debug AWS Secrets

on:
  workflow_dispatch:

jobs:
  debug-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables manually
        run: |
          echo "AWS_ROLE_TO_ASSUME_TF_DEV=${AWS_ROLE_TO_ASSUME_TF_DEV}" >> secrets-debug.txt
          echo "ECR_REPOSITORY_FRONTEND_TF_DEV=${ECR_REPOSITORY_FRONTEND_TF_DEV}" >> secrets-debug.txt
          echo "ECR_REPOSITORY_BACKEND_TF_DEV=${ECR_REPOSITORY_BACKEND_TF_DEV}" >> secrets-debug.txt
          echo "AWS_REGION_TF_DEV=${AWS_REGION_TF_DEV}" >> secrets-debug.txt
        env:
          AWS_ROLE_TO_ASSUME_TF_DEV: ${{ secrets.AWS_ROLE_TO_ASSUME_TF_DEV }}
          ECR_REPOSITORY_FRONTEND_TF_DEV: ${{ secrets.ECR_REPOSITORY_FRONTEND_TF_DEV }}
          ECR_REPOSITORY_BACKEND_TF_DEV: ${{ secrets.ECR_REPOSITORY_BACKEND_TF_DEV }}
          AWS_REGION_TF_DEV: ${{ vars.AWS_REGION_TF_DEV }}

      - name: Show file contents for confirmation (safe to keep)
        run: cat secrets-debug.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: secrets-dump
          path: secrets-debug.txt
